services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    networks:
      - web
    restart: always
    command:
      - "--api.insecure=true"
      - "--accessLog"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
  web:
    external: true

